version: '2.0'

services:
  web:
    build:
      context: .
    ports:
      - 8000:4000
    depends_on:
      - db
    command: 'mix phx.server'
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
